sudo: required
services:
    - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project burner-leskings
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials k8-multi
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t leslielees/k8-multi-test -f ./client/Dockerfile.dev ./client

script:
# we can have test for pther project/containers too. but not doing in this eg.
  - docker run -e CI=true leslielees/k8-multi-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master